FROM node:16-alpine3.11

WORKDIR /api

ENV NODE_ENV=production

COPY package.json package-lock.json ./

RUN apk --no-cache add --virtual builds-deps build-base python3

RUN npm i -g @nestjs/cli
RUN npm i

EXPOSE 3000

CMD ["npm", "run", "start"]
