version: '3.8'
services:
  api:
    container_name: api
    build:
      context: ./backend/api/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/api:/api
      - /api/node_modules
      - /api/dist
    depends_on:
      - db
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: on-failure

  db:
    image: postgres:12.6
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    ports:
      - 5432:5432

volumes:
  postgres:
