name: 'style'

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Images
        run: docker-compose pull

      - name: Restore Cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build
        run: |
          make setup-env
          docker-compose build
      
      - name: Start docker-compose
        run: |
          docker-compose up -d

      - name: Run Prettier
        id: run-prettier
        run: |
          make format_frontend
          make format_backend

      - name: Check Diff
        id: diff-check
        run: |
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Configure GitHub
        if: steps.diff-check.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Push
        if: steps.diff-check.outcome == 'failure'
        run: |
          git commit -m "automated: test"
          git push
